In [1]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 2.1/101.7 MB 12.7 MB/s eta 0:00:08
   - -------------------------------------- 3.4/101.7 MB 10.2 MB/s eta 0:00:10
   - -------------------------------------- 4.2/101.7 MB 7.5 MB/s eta 0:00:14
   - -------------------------------------- 4.7/101.7 MB 6.6 MB/s eta 0:00:15
   -- ------------------------------------- 5.2/101.7 MB 5.4 MB/s eta 0:00:18
   -- ------------------------------------- 5.5/101.7 MB 4.6 MB/s eta 0:00:21
   -- ------------------------------------- 5.8/101.7 MB 4.1 MB/s eta 0:00:24
   -- ------------------------------------- 6.0/101.7 MB 3.8 MB/s eta 0:00:25
   -- ------------------------------------- 6.6/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 7.1/101.7 MB 3.5 MB/s eta 0:00:28
   --- ------------------------------------ 7.9/101.7 MB 3.4 MB/s eta 0:00:28
   --- ------------------------------------ 8.4/101.7 MB 3.4 MB/s eta 0:00:28
   --- ------------------------------------ 9.4/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 10.2/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.3/101.7 MB 3.6 MB/s eta 0:00:26
   ---- ----------------------------------- 12.3/101.7 MB 3.7 MB/s eta 0:00:25
   ----- ---------------------------------- 13.4/101.7 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 14.4/101.7 MB 3.8 MB/s eta 0:00:23
   ----- ---------------------------------- 14.9/101.7 MB 3.8 MB/s eta 0:00:23
   ------ --------------------------------- 15.5/101.7 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 16.0/101.7 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 16.8/101.7 MB 3.6 MB/s eta 0:00:24
   ------ --------------------------------- 17.6/101.7 MB 3.6 MB/s eta 0:00:24
   ------- -------------------------------- 18.4/101.7 MB 3.7 MB/s eta 0:00:23
   ------- -------------------------------- 19.4/101.7 MB 3.7 MB/s eta 0:00:23
   -------- ------------------------------- 20.4/101.7 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 21.2/101.7 MB 3.8 MB/s eta 0:00:22
   -------- ------------------------------- 21.8/101.7 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 22.3/101.7 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 22.8/101.7 MB 3.6 MB/s eta 0:00:22
   --------- ------------------------------ 23.3/101.7 MB 3.6 MB/s eta 0:00:22
   --------- ------------------------------ 23.9/101.7 MB 3.5 MB/s eta 0:00:22
   --------- ------------------------------ 24.4/101.7 MB 3.5 MB/s eta 0:00:22
   --------- ------------------------------ 25.2/101.7 MB 3.5 MB/s eta 0:00:22
   ---------- ----------------------------- 26.0/101.7 MB 3.5 MB/s eta 0:00:22
   ---------- ----------------------------- 26.7/101.7 MB 3.5 MB/s eta 0:00:22
   ---------- ----------------------------- 27.8/101.7 MB 3.6 MB/s eta 0:00:21
   ----------- ---------------------------- 28.8/101.7 MB 3.6 MB/s eta 0:00:21
   ----------- ---------------------------- 29.9/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 30.7/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 31.2/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 31.7/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 32.2/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 33.0/101.7 MB 3.6 MB/s eta 0:00:20
   ------------- -------------------------- 33.6/101.7 MB 3.5 MB/s eta 0:00:20
   ------------- -------------------------- 34.1/101.7 MB 3.5 MB/s eta 0:00:20
   ------------- -------------------------- 34.9/101.7 MB 3.5 MB/s eta 0:00:19
   ------------- -------------------------- 35.4/101.7 MB 3.5 MB/s eta 0:00:19
   -------------- ------------------------- 36.4/101.7 MB 3.5 MB/s eta 0:00:19
   -------------- ------------------------- 37.2/101.7 MB 3.5 MB/s eta 0:00:19
   --------------- ------------------------ 38.3/101.7 MB 3.6 MB/s eta 0:00:18
   --------------- ------------------------ 39.3/101.7 MB 3.6 MB/s eta 0:00:18
   --------------- ------------------------ 40.4/101.7 MB 3.6 MB/s eta 0:00:17
   ---------------- ----------------------- 41.4/101.7 MB 3.6 MB/s eta 0:00:17
   ---------------- ----------------------- 41.9/101.7 MB 3.6 MB/s eta 0:00:17
   ---------------- ----------------------- 42.5/101.7 MB 3.6 MB/s eta 0:00:17
   ---------------- ----------------------- 43.0/101.7 MB 3.6 MB/s eta 0:00:17
   ----------------- ---------------------- 43.5/101.7 MB 3.6 MB/s eta 0:00:17
   ----------------- ---------------------- 44.0/101.7 MB 3.5 MB/s eta 0:00:17
   ----------------- ---------------------- 44.6/101.7 MB 3.5 MB/s eta 0:00:17
   ----------------- ---------------------- 45.4/101.7 MB 3.5 MB/s eta 0:00:16
   ------------------ --------------------- 46.1/101.7 MB 3.5 MB/s eta 0:00:16
   ------------------ --------------------- 46.9/101.7 MB 3.6 MB/s eta 0:00:16
   ------------------ --------------------- 48.0/101.7 MB 3.6 MB/s eta 0:00:16
   ------------------- -------------------- 49.0/101.7 MB 3.6 MB/s eta 0:00:15
   ------------------- -------------------- 49.8/101.7 MB 3.6 MB/s eta 0:00:15
   ------------------- -------------------- 50.3/101.7 MB 3.6 MB/s eta 0:00:15
   ------------------- -------------------- 50.6/101.7 MB 3.6 MB/s eta 0:00:15
   -------------------- ------------------- 51.1/101.7 MB 3.5 MB/s eta 0:00:15
   -------------------- ------------------- 51.4/101.7 MB 3.5 MB/s eta 0:00:15
   -------------------- ------------------- 52.2/101.7 MB 3.5 MB/s eta 0:00:15
   -------------------- ------------------- 53.0/101.7 MB 3.5 MB/s eta 0:00:14
   --------------------- ------------------ 53.7/101.7 MB 3.5 MB/s eta 0:00:14
   --------------------- ------------------ 54.5/101.7 MB 3.5 MB/s eta 0:00:14
   --------------------- ------------------ 55.6/101.7 MB 3.5 MB/s eta 0:00:14
   ---------------------- ----------------- 56.6/101.7 MB 3.5 MB/s eta 0:00:13
   ---------------------- ----------------- 57.7/101.7 MB 3.6 MB/s eta 0:00:13
   ----------------------- ---------------- 58.7/101.7 MB 3.6 MB/s eta 0:00:12
   ----------------------- ---------------- 59.5/101.7 MB 3.6 MB/s eta 0:00:12
   ----------------------- ---------------- 59.8/101.7 MB 3.6 MB/s eta 0:00:12
   ----------------------- ---------------- 60.3/101.7 MB 3.6 MB/s eta 0:00:12
   ----------------------- ---------------- 60.6/101.7 MB 3.5 MB/s eta 0:00:12
   ------------------------ --------------- 61.3/101.7 MB 3.5 MB/s eta 0:00:12
   ------------------------ --------------- 61.9/101.7 MB 3.5 MB/s eta 0:00:12
   ------------------------ --------------- 62.7/101.7 MB 3.5 MB/s eta 0:00:12
   ------------------------- -------------- 63.7/101.7 MB 3.5 MB/s eta 0:00:11
   ------------------------- -------------- 64.5/101.7 MB 3.5 MB/s eta 0:00:11
   ------------------------- -------------- 65.8/101.7 MB 3.6 MB/s eta 0:00:11
   -------------------------- ------------- 66.8/101.7 MB 3.6 MB/s eta 0:00:10
   -------------------------- ------------- 67.9/101.7 MB 3.6 MB/s eta 0:00:10
   --------------------------- ------------ 68.7/101.7 MB 3.6 MB/s eta 0:00:10
   --------------------------- ------------ 69.2/101.7 MB 3.6 MB/s eta 0:00:10
   --------------------------- ------------ 69.7/101.7 MB 3.6 MB/s eta 0:00:09
   --------------------------- ------------ 70.3/101.7 MB 3.6 MB/s eta 0:00:09
   --------------------------- ------------ 71.0/101.7 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 71.8/101.7 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 72.9/101.7 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 73.7/101.7 MB 3.6 MB/s eta 0:00:08
   ----------------------------- ---------- 74.4/101.7 MB 3.6 MB/s eta 0:00:08
   ----------------------------- ---------- 74.7/101.7 MB 3.6 MB/s eta 0:00:08
   ----------------------------- ---------- 75.0/101.7 MB 3.6 MB/s eta 0:00:08
   ----------------------------- ---------- 75.5/101.7 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 76.0/101.7 MB 3.5 MB/s eta 0:00:08
   ------------------------------ --------- 76.5/101.7 MB 3.5 MB/s eta 0:00:08
   ------------------------------ --------- 77.3/101.7 MB 3.5 MB/s eta 0:00:07
   ------------------------------ --------- 78.1/101.7 MB 3.5 MB/s eta 0:00:07
   ------------------------------- -------- 78.9/101.7 MB 3.5 MB/s eta 0:00:07
   ------------------------------- -------- 79.7/101.7 MB 3.5 MB/s eta 0:00:07
   ------------------------------- -------- 80.7/101.7 MB 3.5 MB/s eta 0:00:06
   -------------------------------- ------- 82.1/101.7 MB 3.6 MB/s eta 0:00:06
   -------------------------------- ------- 83.1/101.7 MB 3.6 MB/s eta 0:00:06
   --------------------------------- ------ 84.4/101.7 MB 3.6 MB/s eta 0:00:05
   --------------------------------- ------ 85.2/101.7 MB 3.6 MB/s eta 0:00:05
   --------------------------------- ------ 85.7/101.7 MB 3.6 MB/s eta 0:00:05
   --------------------------------- ------ 86.2/101.7 MB 3.6 MB/s eta 0:00:05
   ---------------------------------- ----- 86.8/101.7 MB 3.6 MB/s eta 0:00:05
   ---------------------------------- ----- 87.3/101.7 MB 3.6 MB/s eta 0:00:05
   ---------------------------------- ----- 87.8/101.7 MB 3.6 MB/s eta 0:00:04
   ---------------------------------- ----- 88.6/101.7 MB 3.6 MB/s eta 0:00:04
   ----------------------------------- ---- 89.4/101.7 MB 3.6 MB/s eta 0:00:04
   ----------------------------------- ---- 90.4/101.7 MB 3.6 MB/s eta 0:00:04
   ----------------------------------- ---- 91.2/101.7 MB 3.6 MB/s eta 0:00:03
   ------------------------------------ --- 92.3/101.7 MB 3.6 MB/s eta 0:00:03
   ------------------------------------ --- 92.8/101.7 MB 3.6 MB/s eta 0:00:03
   ------------------------------------ --- 93.6/101.7 MB 3.6 MB/s eta 0:00:03
   ------------------------------------- -- 94.1/101.7 MB 3.6 MB/s eta 0:00:03
   ------------------------------------- -- 94.9/101.7 MB 3.6 MB/s eta 0:00:02
   ------------------------------------- -- 95.7/101.7 MB 3.6 MB/s eta 0:00:02
   ------------------------------------- -- 95.9/101.7 MB 3.6 MB/s eta 0:00:02
   -------------------------------------- - 96.7/101.7 MB 3.6 MB/s eta 0:00:02
   -------------------------------------- - 97.3/101.7 MB 3.6 MB/s eta 0:00:02
   -------------------------------------- - 98.0/101.7 MB 3.6 MB/s eta 0:00:02
   -------------------------------------- - 98.8/101.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  99.6/101.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  100.7/101.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 3.5 MB/s  0:00:28
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [2]:
import xgboost as xg

In [3]:
import pandas as pd
dataset=pd.read_csv("insurance_pre - insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [10]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [14]:
from xgboost import XGBRegressor
regressor = XGBRegressor(n_estimators=100,learning_rate=0.1,max_depth=3,subsample=0.8,colsample_bytree=0.8 )
regressor.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [15]:
y_pred=regressor.predict(x_test)

In [16]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8850474953651428

In [17]:
import pickle
filename='BestRegressionModelXGBoost.sav'
pickle.dump(regressor,open(filename, 'wb'))

In [18]:
loaded_model=pickle.load(open('BestRegressionModelLGBBoost.sav', 'rb'))
result=loaded_model.predict([[19, 21, 30, 0, 1]])
result

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

array([16654.75589658])